/**
 * Localization messages for CssSortify extension
 */

const messages = {
  en: {
    sortSuccess: "CSS properties sorted successfully!",
    notCssFile: "This is not a CSS file.",
    notHtmlFile: "This is not an HTML file.",
    noStyleTagsFound: "No style tags found in the HTML file.",
    noHeadTagFound: "No head tag found in the HTML file.",
    cssExtractSuccess: "CSS extracted successfully to {0}",
    cssExtractFailed: "Failed to extract CSS: {0}",
    noInlineStylesFound: "No inline styles found in the HTML file.",
    inlineStylesConverted: "Inline styles converted to classes successfully!",
    selectedInlineStyleConverted:
      "Selected element's inline style converted to class successfully!",
    minifySuccess: "CSS minified successfully!",
    minifySaveSuccess: "Minified CSS saved to {0}",
    minifyFailed: "Failed to minify CSS: {0}",
    cssSortingFailed: "CSS sorting failed: {0}",
    cssSortFailed: "CSS sorting failed: {0}",
    cssMinifySuccess: "CSS minified successfully and saved to {0}",
    cssMinifyInPlaceSuccess: "CSS minified successfully in-place",
    cssMinifyFailed: "Failed to minify CSS: {0}",
  },
  tr: {
    sortSuccess: "CSS özellikleri başarıyla sıralandı!",
    notCssFile: "Bu bir CSS dosyası değil.",
    notHtmlFile: "Bu bir HTML dosyası değil.",
    noStyleTagsFound: "HTML dosyasında style etiketi bulunamadı.",
    noHeadTagFound: "HTML dosyasında head etiketi bulunamadı.",
    cssExtractSuccess: "CSS başarıyla {0} dosyasına çıkarıldı",
    cssExtractFailed: "CSS çıkarma başarısız: {0}",
    noInlineStylesFound: "HTML dosyasında inline style bulunamadı.",
    inlineStylesConverted:
      "Inline style'lar başarıyla class'lara dönüştürüldü!",
    selectedInlineStyleConverted:
      "Seçili elementin inline style'ı başarıyla class'a dönüştürüldü!",
    minifySuccess: "CSS başarıyla küçültüldü!",
    minifySaveSuccess: "Küçültülmüş CSS {0} dosyasına kaydedildi",
    minifyFailed: "CSS küçültme başarısız: {0}",
    cssSortingFailed: "CSS sıralama başarısız: {0}",
    cssSortFailed: "CSS sıralama başarısız: {0}",
    cssMinifySuccess: "CSS başarıyla küçültüldü ve {0} dosyasına kaydedildi",
    cssMinifyInPlaceSuccess: "CSS başarıyla yerinde küçültüldü",
    cssMinifyFailed: "CSS küçültme başarısız: {0}",
  },
  de: {
    sortSuccess: "CSS-Eigenschaften erfolgreich sortiert!",
    notCssFile: "Dies ist keine CSS-Datei.",
    notHtmlFile: "Dies ist keine HTML-Datei.",
    noStyleTagsFound: "Keine Style-Tags in der HTML-Datei gefunden.",
    noHeadTagFound: "Kein Head-Tag in der HTML-Datei gefunden.",
    cssExtractSuccess: "CSS erfolgreich nach {0} extrahiert",
    cssExtractFailed: "CSS-Extraktion fehlgeschlagen: {0}",
    noInlineStylesFound: "Keine Inline-Styles in der HTML-Datei gefunden.",
    inlineStylesConverted: "Inline-Styles erfolgreich in Klassen umgewandelt!",
    selectedInlineStyleConverted:
      "Inline-Style des ausgewählten Elements erfolgreich in Klasse umgewandelt!",
    minifySuccess: "CSS erfolgreich minimiert!",
    minifySaveSuccess: "Minimiertes CSS gespeichert unter {0}",
    minifyFailed: "CSS-Minimierung fehlgeschlagen: {0}",
    cssSortingFailed: "CSS-Sortierung fehlgeschlagen: {0}",
    cssMinifyInPlaceSuccess: "CSS erfolgreich minimiert!",
    cssMinifyFailed: "CSS-Minimierung fehlgeschlagen: {0}",
  },
  ru: {
    sortSuccess: "Свойства CSS успешно отсортированы!",
    notCssFile: "Это не CSS файл.",
    notHtmlFile: "Это не HTML файл.",
    noStyleTagsFound: "В HTML файле не найдены теги style.",
    noHeadTagFound: "В HTML файле не найден тег head.",
    cssExtractSuccess: "CSS успешно извлечен в {0}",
    cssExtractFailed: "Не удалось извлечь CSS: {0}",
    noInlineStylesFound: "В HTML файле не найдены встроенные стили.",
    inlineStylesConverted: "Встроенные стили успешно преобразованы в классы!",
    selectedInlineStyleConverted:
      "Встроенный стиль выбранного элемента успешно преобразован в класс!",
    minifySuccess: "CSS успешно минимизирован!",
    minifySaveSuccess: "Минимизированный CSS сохранен в {0}",
    minifyFailed: "Не удалось минимизировать CSS: {0}",
    cssSortingFailed: "Сортировка CSS не удалась: {0}",
    cssMinifyInPlaceSuccess: "CSS успешно минимизирован!",
    cssMinifyFailed: "Не удалось минимизировать CSS: {0}",
  },
  zh: {
    sortSuccess: "CSS属性排序成功！",
    notCssFile: "这不是CSS文件。",
    notHtmlFile: "这不是HTML文件。",
    noStyleTagsFound: "在HTML文件中未找到样式标签。",
    noHeadTagFound: "在HTML文件中未找到head标签。",
    cssExtractSuccess: "CSS成功提取到{0}",
    cssExtractFailed: "CSS提取失败：{0}",
    noInlineStylesFound: "在HTML文件中未找到内联样式。",
    inlineStylesConverted: "内联样式成功转换为类！",
    selectedInlineStyleConverted: "所选元素的内联样式成功转换为类！",
    minifySuccess: "CSS压缩成功！",
    minifySaveSuccess: "压缩后的CSS已保存到{0}",
    minifyFailed: "CSS压缩失败：{0}",
    cssSortingFailed: "CSS排序失败：{0}",
    cssMinifyInPlaceSuccess: "CSS压缩成功！",
    cssMinifyFailed: "CSS压缩失败：{0}",
  }
};

module.exports = { messages };
